name: workflow1
on: push
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
          - name: Get code
            uses: actions/checkout@v3
          - name: npm Install
            run: npm install
          - name: Install dependencies
            run: npm ci
          - name: lint
            run: npm run lint
          - name: test
            run: npm run test
          - name: build
            run: npm run build